[package]
name = "gol_piston"
version = "0.1.0"
authors = ["Pascal Winkelmann <pascal@wnklmnn.de>"]
edition = "2018"

[dependencies]
piston_window = "0.89.0"
image = "0.22.5"
piston2d-graphics = "0.30.0"
rust_gol = { path = "../lib" }
rand = "0.6.5"
